---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: rummager
    # redis server is included because app needs it to run
    run_list: ["recipe[redis::server]", "recipe[odi-rummager-node]"]
    attributes:
    data_bags_path: test/data_bags
